/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import DomainModels.ChiTietSanPham;
import DomainModels.GioHang;
import DomainModels.GioHangChiTiet;
import DomainModels.KhachHang;
import DomainModels.NhanVien;
import Services.GHCTservice;
import Services.GioHangService;
import Services.ServiceCTSP;
import Services.ServiceKhachHang;
import Services.ServiceNhanvien;
import Services.impl.GHCTserviceImpl;
import Services.impl.GioHangServiceImpl;
import Services.impl.ServiceCTSPImpl;
import Services.impl.ServiceKhachHangImpl;
import Services.impl.ServiceNhanVienImpl;
import ViewModels.ChiTietSanPhamModels;
import ViewModels.GioHangViewModels;
import ViewModels.KhachHangViewModels;
import ViewModels.NHanVienViewModels;

import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diệm DZ
 */
public class ViewGioHang extends javax.swing.JInternalFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm1 = new DefaultTableModel();
    private DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm1 = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm3 = new DefaultComboBoxModel();
    private GioHangService gioHangService = new GioHangServiceImpl();
    private ServiceKhachHang serviceKhachHang = new ServiceKhachHangImpl();
    private ServiceNhanvien serviceNhanvien = new ServiceNhanVienImpl();
    private ServiceCTSP serviceCTSP = new ServiceCTSPImpl();
    private GHCTservice gHCTservice = new GHCTserviceImpl();
    private List<KhachHangViewModels> listKH = serviceKhachHang.getAll();
    private List<NHanVienViewModels> listNV = serviceNhanvien.getAll();
    private List<GioHangViewModels> listGH = gioHangService.getAll();
    private List<ChiTietSanPhamModels> listCTSP = serviceCTSP.getAllSanPham();

    /**
     * Creates new form ViewGioHang
     */
    public ViewGioHang() {
        initComponents();
        cbbTenKhachHang1.setModel(dcm);
        for (KhachHangViewModels x : listKH) {
            dcm.addElement(x.getTen());
        }
        cbbtenNhanVien.setModel(dcm1);
        for (NHanVienViewModels x : listNV) {
            dcm1.addElement(x.getTen());
        }
        cbbIDGiohang.setModel(dcm2);
        for (GioHangViewModels x : listGH) {
            dcm2.addElement(gioHangService.getId(x.getMa()).getiD());
        }
        cbbIDChiTietSp.setModel(dcm3);
        for (ChiTietSanPhamModels x : listCTSP) {
            dcm3.addElement(x.getiD());
        }
        jTableGioHang.setModel(dtm);
        String[] a = {"Mã", "Ngày tạo", "Ngày thanh toán", "Tên người nhận", "Địa chỉ", "SDT", "Trạng thái"};
        dtm.setColumnIdentifiers(a);
        showData(gioHangService.getAll());
        jTableGioHangChiTiet.setModel(dtm1);
        String[] b = {"ID Giỏ Hàng", "ID CTSP", "Số lượng", "Đơn giá", "Đơn giá khi giảm"};
        dtm1.setColumnIdentifiers(b);
        showDataGHCT(gHCTservice.getAll());
    }

    private void showData(List<GioHangViewModels> list) {
        dtm.setRowCount(0);
        for (GioHangViewModels x : list) {
            dtm.addRow(x.toRowData());
        }
    }

    private void showDataGHCT(List<GioHangChiTiet> list) {
        dtm1.setRowCount(0);
        for (GioHangChiTiet x : list) {
            dtm1.addRow(x.toRowData());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGioHang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemGioHang = new javax.swing.JTextField();
        btnTimKiemGiohang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdGioHang = new javax.swing.JTextField();
        cbbtenNhanVien = new javax.swing.JComboBox<>();
        txtMaGioHang = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtNgayThanhToan = new javax.swing.JTextField();
        txtTenNguoiNhan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienthoai = new javax.swing.JTextField();
        rbConHang = new javax.swing.JRadioButton();
        rbHetHang = new javax.swing.JRadioButton();
        cbbTenKhachHang1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnMoiGioHang = new javax.swing.JButton();
        btnXoaGiohang = new javax.swing.JButton();
        btnThemGiohang = new javax.swing.JButton();
        btnSuaGiohang = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGioHangChiTiet = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbbIDGiohang = new javax.swing.JComboBox<>();
        cbbIDChiTietSp = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        txtdonGia = new javax.swing.JTextField();
        txtDongiakhigiam = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnMoiGHCT = new javax.swing.JButton();
        btnXoaGHCT = new javax.swing.JButton();
        btnThemGHCT = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1149, 664));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTableGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGioHang);

        jLabel1.setText("Tìm kiếm");

        btnTimKiemGiohang.setText("Tìm kiếm");
        btnTimKiemGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemGiohangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemGiohang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTimKiemGiohang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Id");

        jLabel4.setText("Tên khách hàng");

        jLabel5.setText("Tên nhân viên");

        jLabel6.setText("Mã");

        jLabel7.setText("Ngày tạo");

        jLabel8.setText("Ngày thanh toán");

        jLabel9.setText("Tên người nhận");

        jLabel10.setText("Địa chỉ");

        jLabel11.setText("Số điện thoại");

        jLabel12.setText("Tình trạng");

        txtIdGioHang.setEnabled(false);

        cbbtenNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rbConHang);
        rbConHang.setSelected(true);
        rbConHang.setText("Còn hàng");

        buttonGroup1.add(rbHetHang);
        rbHetHang.setText("Hết hàng");

        cbbTenKhachHang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        btnMoiGioHang.setText("Mới");
        btnMoiGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiGioHangActionPerformed(evt);
            }
        });

        btnXoaGiohang.setText("Xóa");
        btnXoaGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaGiohangActionPerformed(evt);
            }
        });

        btnThemGiohang.setText("Thêm");
        btnThemGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGiohangActionPerformed(evt);
            }
        });

        btnSuaGiohang.setText("Sửa");
        btnSuaGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaGiohangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMoiGioHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemGiohang))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnSuaGiohang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaGiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemGiohang)
                    .addComponent(btnMoiGioHang))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaGiohang)
                    .addComponent(btnXoaGiohang))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbConHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbHetHang)
                        .addContainerGap(271, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdGioHang)
                            .addComponent(cbbtenNhanVien, 0, 141, Short.MAX_VALUE)
                            .addComponent(txtMaGioHang)
                            .addComponent(txtNgayTao)
                            .addComponent(txtNgayThanhToan)
                            .addComponent(txtTenNguoiNhan)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSoDienthoai)
                            .addComponent(cbbTenKhachHang1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbTenKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbtenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTenNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoDienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rbConHang)
                    .addComponent(rbHetHang))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập nhập", jPanel2);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableGioHangChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGioHangChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGioHangChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGioHangChiTiet);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cập nhập", jPanel4);

        jLabel13.setText("ID Giỏ Hàng");
        jLabel13.setToolTipText("");

        jLabel14.setText("ID Chi tiết SP");

        jLabel15.setText("Số lượng");

        jLabel16.setText("Đơn giá");

        jLabel17.setText("Đơn giá khi giảm");

        cbbIDGiohang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbIDChiTietSp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        btnMoiGHCT.setText("Mới");
        btnMoiGHCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiGHCTActionPerformed(evt);
            }
        });

        btnXoaGHCT.setText("Xóa");
        btnXoaGHCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaGHCTActionPerformed(evt);
            }
        });

        btnThemGHCT.setText("Thêm");
        btnThemGHCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGHCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnXoaGHCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnMoiGHCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemGHCT)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemGHCT)
                    .addComponent(btnMoiGHCT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaGHCT)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbIDGiohang, 0, 200, Short.MAX_VALUE)
                            .addComponent(cbbIDChiTietSp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong)
                            .addComponent(txtdonGia)
                            .addComponent(txtDongiakhigiam)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbbIDGiohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbbIDChiTietSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDongiakhigiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(34, 34, 34)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Danh sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiGioHangActionPerformed
        // TODO add your handling code here:

        txtIdGioHang.setText("");
        cbbTenKhachHang1.setSelectedIndex(0);
        cbbtenNhanVien.setSelectedIndex(0);
        txtMaGioHang.setText("");
        txtNgayTao.setText("");
        txtNgayThanhToan.setText("");
        txtTenNguoiNhan.setText("");
        txtDiaChi.setText("");
        txtSoDienthoai.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnMoiGioHangActionPerformed

    private void btnXoaGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaGiohangActionPerformed
        // TODO add your handling code here:
        String id = txtIdGioHang.getText();
        JOptionPane.showMessageDialog(this, gioHangService.delete(id));
        showData(gioHangService.getAll());
    }//GEN-LAST:event_btnXoaGiohangActionPerformed

    private void btnThemGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGiohangActionPerformed
        // TODO add your handling code here:
        String tenKhachHang = cbbTenKhachHang1.getSelectedItem().toString();
        String tenNhanVien = cbbtenNhanVien.getSelectedItem().toString();
        String ma = txtMaGioHang.getText();
        String ngaytao = txtNgayTao.getText();
        String ngayThanhtoan = txtNgayThanhToan.getText();
        String tenNguoiNhan = txtTenNguoiNhan.getText();
        String diaChi = txtDiaChi.getText();
        String sDT = txtSoDienthoai.getText();
        int tinhTrang;
        if (rbConHang.isSelected()) {
            tinhTrang = 0;
        } else {
            tinhTrang = 1;
        }
        GioHang gh = new GioHang(new KhachHang(serviceKhachHang.getIdByTen(tenKhachHang).getiD()), new NhanVien(serviceNhanvien.getIdByTen(tenNhanVien).getiD()), ma, Date.valueOf(ngaytao), Date.valueOf(ngayThanhtoan), tenNguoiNhan, diaChi, sDT, tinhTrang);
        JOptionPane.showMessageDialog(this, gioHangService.add(gh));
        showData(gioHangService.getAll());
    }//GEN-LAST:event_btnThemGiohangActionPerformed

    private void btnSuaGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaGiohangActionPerformed
        // TODO add your handling code here:
        String id = txtIdGioHang.getText();
        String tenKhachHang = cbbTenKhachHang1.getSelectedItem().toString();
        String tenNhanVien = cbbtenNhanVien.getSelectedItem().toString();
        String ma = txtMaGioHang.getText();
        String ngaytao = txtNgayTao.getText();
        String ngayThanhtoan = txtNgayThanhToan.getText();
        String tenNguoiNhan = txtTenNguoiNhan.getText();
        String diaChi = txtDiaChi.getText();
        String sDT = txtSoDienthoai.getText();
        int tinhTrang;
        if (rbConHang.isSelected()) {
            tinhTrang = 0;
        } else {
            tinhTrang = 1;
        }
        GioHang gh = new GioHang(new KhachHang(serviceKhachHang.getIdByTen(tenKhachHang).getiD()), new NhanVien(serviceNhanvien.getIdByTen(tenNhanVien).getiD()), ma, Date.valueOf(ngaytao), Date.valueOf(ngayThanhtoan), tenNguoiNhan, diaChi, sDT, tinhTrang);
        JOptionPane.showMessageDialog(this, gioHangService.update(gh, id));
        showData(gioHangService.getAll());
    }//GEN-LAST:event_btnSuaGiohangActionPerformed

    private void btnMoiGHCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiGHCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoiGHCTActionPerformed

    private void btnXoaGHCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaGHCTActionPerformed
        // TODO add your handling code here:
        String id = txtIdGioHang.getText();
        JOptionPane.showMessageDialog(this, gHCTservice.delete(id));
        showDataGHCT(gHCTservice.getAll());
    }//GEN-LAST:event_btnXoaGHCTActionPerformed

    private void btnThemGHCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGHCTActionPerformed
        // TODO add your handling code here:
        String idGioHang =cbbIDGiohang.getSelectedItem().toString();
        String idCTSP = cbbIDChiTietSp.getSelectedItem().toString();
        String soLuong = txtSoLuong.getText();
        String donGia = txtdonGia.getText();
        String donGiaKhiGiam = txtdonGia.getText();
        
        GioHangChiTiet ghct = new GioHangChiTiet(new GioHang(idGioHang), new ChiTietSanPham(idCTSP), Integer.valueOf(soLuong), Double.valueOf(donGia), Double.valueOf(donGiaKhiGiam));
        JOptionPane.showMessageDialog(this, gHCTservice.add(ghct));
        showDataGHCT(gHCTservice.getAll());
    }//GEN-LAST:event_btnThemGHCTActionPerformed

    private void jTableGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGioHangMouseClicked
        // TODO add your handling code here:
        int row = jTableGioHang.getSelectedRow();
        GioHangViewModels gh = gioHangService.getAll().get(row);
        String ma = gh.getMa();
        txtIdGioHang.setText(gioHangService.getId(ma).getiD());
        cbbTenKhachHang1.setSelectedItem(gioHangService.getId(ma).getKhachHang().getiD());
        cbbtenNhanVien.setSelectedItem(gioHangService.getId(ma).getNhanVien().getiD());
        txtMaGioHang.setText(ma);
        txtNgayTao.setText(String.valueOf(gh.getNgayTao()));
        txtNgayThanhToan.setText(String.valueOf(gh.getNgayThanhToan()));
        txtTenNguoiNhan.setText(gh.getTenNguoiNhan());
        txtDiaChi.setText(gh.getDiaChi());
        txtSoDienthoai.setText(gh.getSoDienThoai());
        if (gh.getTinhTrang() == 0) {
            rbConHang.setSelected(true);
        } else {
            rbHetHang.setSelected(true);
        }
    }//GEN-LAST:event_jTableGioHangMouseClicked

    private void jTableGioHangChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGioHangChiTietMouseClicked
        // TODO add your handling code here:
        int row = jTableGioHangChiTiet.getSelectedRow();
        GioHangChiTiet ghct = gHCTservice.getAll().get(row);
        cbbIDGiohang.setSelectedItem(ghct.getGioHang().getiD());
        cbbIDChiTietSp.setSelectedItem(ghct.getChiTietSanPham().getiD());
        txtdonGia.setText(String.valueOf(ghct.getDonGia()));
        txtSoLuong.setText(String.valueOf(ghct.getSoLuong()));
        txtDongiakhigiam.setText(String.valueOf(ghct.getDongiaKhiGiam()));
    }//GEN-LAST:event_jTableGioHangChiTietMouseClicked

    private void btnTimKiemGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemGiohangActionPerformed
        // TODO add your handling code here:
        String ma = txtTimKiemGioHang.getText();
        List<GioHangViewModels> listNew = gioHangService.search(gioHangService.getAll(), ma);
        showData(listNew);
    }//GEN-LAST:event_btnTimKiemGiohangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoiGHCT;
    private javax.swing.JButton btnMoiGioHang;
    private javax.swing.JButton btnSuaGiohang;
    private javax.swing.JButton btnThemGHCT;
    private javax.swing.JButton btnThemGiohang;
    private javax.swing.JButton btnTimKiemGiohang;
    private javax.swing.JButton btnXoaGHCT;
    private javax.swing.JButton btnXoaGiohang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbIDChiTietSp;
    private javax.swing.JComboBox<String> cbbIDGiohang;
    private javax.swing.JComboBox<String> cbbTenKhachHang1;
    private javax.swing.JComboBox<String> cbbtenNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableGioHang;
    private javax.swing.JTable jTableGioHangChiTiet;
    private javax.swing.JRadioButton rbConHang;
    private javax.swing.JRadioButton rbHetHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDongiakhigiam;
    private javax.swing.JTextField txtIdGioHang;
    private javax.swing.JTextField txtMaGioHang;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNgayThanhToan;
    private javax.swing.JTextField txtSoDienthoai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenNguoiNhan;
    private javax.swing.JTextField txtTimKiemGioHang;
    private javax.swing.JTextField txtdonGia;
    // End of variables declaration//GEN-END:variables
}
