/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;


import DomainModels.ChiTietSanPham;
import DomainModels.DongSp;
import DomainModels.MauSac;
import DomainModels.NSX;
import DomainModels.SanPham;
import Services.ServiceCTSP;
import Services.ServiceDongSp;
import Services.ServiceMauSac;
import Services.ServiceNSX;
import Services.ServiceSanPham;
import Services.impl.ServiceCTSPImpl;
import Services.impl.ServiceDongSpImpl;
import Services.impl.ServiceMauSacImpl;
import Services.impl.ServiceNSXImpl;
import Services.impl.ServiceSanPhamImpl;
import ViewModels.ChiTietSanPhamModels;


import javax.swing.table.DefaultTableModel;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Diệm DZ
 */
public  class ViewSanPham extends javax.swing.JInternalFrame {
    private DefaultTableModel dtm1 = new DefaultTableModel();
    private DefaultTableModel dtm2 = new DefaultTableModel();
    
    private DefaultComboBoxModel dcm1 = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm3 = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcm4 = new DefaultComboBoxModel();
    
    private  ServiceSanPham ql = new ServiceSanPhamImpl();
    private ServiceNSX qlNSX = new ServiceNSXImpl();
    private ServiceMauSac qlMau = new ServiceMauSacImpl();
    private ServiceDongSp qlDong = new ServiceDongSpImpl();
    private  ServiceCTSP qlCtsp = new ServiceCTSPImpl();
    
    private List<SanPham> listSp = ql.getAll();
    private List<NSX> listNSX = qlNSX.getAllNSX();
    private List<MauSac> listMau = qlMau.getAllMauSac();
    private List<DongSp> listDong = qlDong.getAllDongSp();
    /**
     * Creates new form add
     */
    public ViewSanPham() {
        initComponents();
        
        cbbIDSP.setModel(dcm1);
        for (SanPham x : listSp) {
            dcm1.addElement(x.getTen());
        }
        cbbIDNSX.setModel(dcm2);
        for (NSX x : listNSX) {
            dcm2.addElement(x.getTen());
        }
        cbbIDMauSac.setModel(dcm3);
        for (MauSac x : listMau) {
            dcm3.addElement(x.getTen());
        }
        cbbIDDongSp.setModel(dcm4);
        for (DongSp x : listDong) {
            dcm4.addElement(x.getTen());
        }
        jTableSanPham.setModel(dtm1);
        String [] sp = {"Id","Mã SP","Tên SP"};
        dtm1.setColumnIdentifiers(sp);
        showDataSanPham(ql.getAll());
        
        jTableSPCT.setModel(dtm2);
        String [] spct ={"Id","IDsp","Năm BH","Mô tả","Số lượng","Giá nhập","Giá bán"};
        dtm2.setColumnIdentifiers(spct);
        showDataCTSP(qlCtsp.getAllSanPham());
    }
    private void addcbbIDSp(List<SanPham> list){
        dcm1 = (DefaultComboBoxModel) cbbIDSP.getModel();
        for (SanPham x : list) {
            dcm1.addElement(x);
        }
    }
   private void showDataSanPham(List<SanPham> list){
        dtm1.setRowCount(0);
        for (SanPham x : list) {
            dtm1.addRow(x.toRowData());
        }
    }
    private void showDataCTSP(List<ChiTietSanPhamModels> list){
        dtm2.setRowCount(0);
        for (ChiTietSanPhamModels x : list) {
            dtm2.addRow(x.toRowData());
        }
    }
    private void fillDataSanPHam(int index){
        SanPham sp = ql.getAll().get(index);
        txtID.setText(String.valueOf(sp.getiD()));
        txtMa.setText(sp.getMa());
        txtTen.setText(sp.getTen());
    }
    private void fillDataCTSP(int index){
        ChiTietSanPhamModels ctsp = qlCtsp.getAllSanPham().get(index);
       
        txtIDCTSP.setText(String.valueOf(ctsp.getiD()));
         String id = ctsp.getiD();
        cbbIDSP.setSelectedItem(String.valueOf(qlCtsp.getID(id).getSanPham().getiD()));
        cbbIDNSX.setSelectedItem(String.valueOf(qlCtsp.getID(id).getNsx().getiD()));
        cbbIDMauSac.setSelectedItem(String.valueOf(qlCtsp.getID(id).getMauSac().getiD()));
        cbbIDDongSp.setSelectedItem(String.valueOf(qlCtsp.getID(id).getDongSp().getiD()));
        
        txtNBH.setText(String.valueOf(ctsp.getNamBaoHanh()));
        txtMoTa.setText(ctsp.getMoTa());
        txtsoLuong.setText(String.valueOf(ctsp.getSoLuong()));
        txtGiaNhap.setText(String.valueOf(ctsp.getGiaNhap()));
        txtGiaBan.setText(String.valueOf(ctsp.getGiaBan()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNBH = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        txtsoLuong = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        btnNewCTSP = new javax.swing.JButton();
        btnAddCTSP = new javax.swing.JButton();
        btnUpdateCTSP = new javax.swing.JButton();
        btndeleteCTSP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIDCTSP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbbIDSP = new javax.swing.JComboBox<>();
        cbbIDNSX = new javax.swing.JComboBox<>();
        cbbIDMauSac = new javax.swing.JComboBox<>();
        cbbIDDongSp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        btnNewSanPham = new javax.swing.JButton();
        btnAddSP = new javax.swing.JButton();
        btnUpdatesanPham = new javax.swing.JButton();
        btndeletesanPham = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSPCT = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1149, 664));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 664));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Năm bảo hành");

        jLabel4.setText("Mô tả");

        jLabel5.setText("Màu Sắc");
        jLabel5.setToolTipText("");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Giá nhập");

        jLabel8.setText("Giá bán");

        btnNewCTSP.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Refresh.png")); // NOI18N
        btnNewCTSP.setText("New");
        btnNewCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCTSPActionPerformed(evt);
            }
        });

        btnAddCTSP.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Add.png")); // NOI18N
        btnAddCTSP.setText("Add");
        btnAddCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCTSPActionPerformed(evt);
            }
        });

        btnUpdateCTSP.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Edit.png")); // NOI18N
        btnUpdateCTSP.setText("Update");
        btnUpdateCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCTSPActionPerformed(evt);
            }
        });

        btndeleteCTSP.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Delete.png")); // NOI18N
        btndeleteCTSP.setText("Delete");
        btndeleteCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteCTSPActionPerformed(evt);
            }
        });

        jLabel10.setText("Sản phẩm");

        jLabel11.setText("ID");

        txtIDCTSP.setEnabled(false);

        jLabel13.setText("NSX");

        jLabel14.setText("Dòng");

        cbbIDSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbIDNSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbIDMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbIDDongSp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(btnNewCTSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddCTSP)
                        .addGap(14, 14, 14)
                        .addComponent(btnUpdateCTSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeleteCTSP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel7))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtIDCTSP, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtNBH, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtsoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(cbbIDSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbIDNSX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbIDMauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbIDDongSp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIDCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbIDNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbIDMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbbIDDongSp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNBH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCTSP)
                    .addComponent(btnAddCTSP)
                    .addComponent(btnUpdateCTSP)
                    .addComponent(btndeleteCTSP))
                .addGap(35, 35, 35))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tên Sản phẩm");

        jLabel2.setText("Mã SP");

        btnNewSanPham.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Refresh.png")); // NOI18N
        btnNewSanPham.setText("New");
        btnNewSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSanPhamActionPerformed(evt);
            }
        });

        btnAddSP.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Add.png")); // NOI18N
        btnAddSP.setText("Add");
        btnAddSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSPActionPerformed(evt);
            }
        });

        btnUpdatesanPham.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Edit.png")); // NOI18N
        btnUpdatesanPham.setText("Update");
        btnUpdatesanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatesanPhamActionPerformed(evt);
            }
        });

        btndeletesanPham.setIcon(new javax.swing.ImageIcon("E:\\SOF204_DuAnMau\\Tai nguyen sinh vien\\Tai nguyen khac\\Hinh\\Delete.png")); // NOI18N
        btndeletesanPham.setText("Delete");
        btndeletesanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletesanPhamActionPerformed(evt);
            }
        });

        jLabel9.setText("ID ");

        txtID.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtTen))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnNewSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdatesanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeletesanPham)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeletesanPham)
                    .addComponent(btnUpdatesanPham)
                    .addComponent(btnAddSP)
                    .addComponent(btnNewSanPham))
                .addGap(50, 50, 50))
        );

        jTableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSanPham);

        jTableSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSPCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSPCT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSPActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        
        SanPham sp = new SanPham(ma, ten);
        JOptionPane.showMessageDialog(this, ql.add(sp));
        showDataSanPham(ql.getAll());
    }//GEN-LAST:event_btnAddSPActionPerformed

    private void btnUpdatesanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatesanPhamActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        
        SanPham sp = new SanPham(id,ma, ten);
       
        JOptionPane.showMessageDialog(this, ql.update(sp, id));
        showDataSanPham(ql.getAll());
    }//GEN-LAST:event_btnUpdatesanPhamActionPerformed

    private void btndeletesanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletesanPhamActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        JOptionPane.showMessageDialog(this, ql.delete(id));
        showDataSanPham(ql.getAll());
    }//GEN-LAST:event_btndeletesanPhamActionPerformed

    private void btnNewSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSanPhamActionPerformed
         // TODO add your handling code here:
          txtID.setText("");
        txtMa.setText("");
        txtTen.setText("");
    }//GEN-LAST:event_btnNewSanPhamActionPerformed

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        // TODO add your handling code here:
        int row = jTableSanPham.getSelectedRow();
        fillDataSanPHam(row);
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void btnNewCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCTSPActionPerformed
        // TODO add your handling code here:
        
        txtIDCTSP.setText("");
        cbbIDSP.setSelectedIndex(0);
        txtNBH.setText("");
        txtMoTa.setText("");
        cbbIDMauSac.setSelectedIndex(0);
        txtsoLuong.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
       cbbIDNSX.setSelectedIndex(0);
       cbbIDDongSp.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewCTSPActionPerformed
         
    private void btnAddCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCTSPActionPerformed
        // TODO add your handling code here:
      
        String tenSp = cbbIDSP.getSelectedItem().toString();
        String teNSX = cbbIDNSX.getSelectedItem().toString();
        String tenMauSac = cbbIDMauSac.getSelectedItem().toString();
        String tenDong = cbbIDDongSp.getSelectedItem().toString();
        String namBH = txtNBH.getText();
        String moTa = txtMoTa.getText();
        String soLuong = txtsoLuong.getText();
        String giaNhap = txtGiaNhap.getText();
        String giaBan = txtGiaBan.getText();
        ChiTietSanPham ctsp = new ChiTietSanPham(new SanPham(ql.getIdByTen(tenSp).getiD()), new NSX(qlNSX.getIdByTen(teNSX).getiD()), new MauSac(qlMau.getIdByTen(tenMauSac).getiD()), new DongSp(qlDong.getIdByTen(tenDong).getiD()), Integer.valueOf(namBH), moTa, Integer.valueOf(soLuong), Double.valueOf(giaNhap), Double.valueOf(giaBan));
        JOptionPane.showMessageDialog(this, qlCtsp.add(ctsp));
        showDataCTSP(qlCtsp.getAllSanPham());
    }//GEN-LAST:event_btnAddCTSPActionPerformed

    private void btnUpdateCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCTSPActionPerformed
        // TODO add your handling code here:
        String id = txtIDCTSP.getText();
          
        String tenSp = cbbIDSP.getSelectedItem().toString();
        String teNSX = cbbIDNSX.getSelectedItem().toString();
        String tenMauSac = cbbIDMauSac.getSelectedItem().toString();
        String tenDong = cbbIDDongSp.getSelectedItem().toString();
        String namBH = txtNBH.getText();
        String moTa = txtMoTa.getText();
        String soLuong = txtsoLuong.getText();
        String giaNhap = txtGiaNhap.getText();
        String giaBan = txtGiaBan.getText();
        ChiTietSanPham ctsp = new ChiTietSanPham(new SanPham(ql.getIdByTen(tenSp).getiD()), new NSX(qlNSX.getIdByTen(teNSX).getiD()), new MauSac(qlMau.getIdByTen(tenMauSac).getiD()), new DongSp(qlDong.getIdByTen(tenDong).getiD()), Integer.valueOf(namBH), moTa, Integer.valueOf(soLuong), Double.valueOf(giaNhap), Double.valueOf(giaBan));
        JOptionPane.showMessageDialog(this, qlCtsp.update(ctsp, id));
        showDataCTSP(qlCtsp.getAllSanPham());
    }//GEN-LAST:event_btnUpdateCTSPActionPerformed

    private void btndeleteCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteCTSPActionPerformed
        // TODO add your handling code here:
        String id = txtIDCTSP.getText();
          JOptionPane.showMessageDialog(this, qlCtsp.delete(id));
        showDataCTSP(qlCtsp.getAllSanPham());
    }//GEN-LAST:event_btndeleteCTSPActionPerformed

    private void jTableSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSPCTMouseClicked
        // TODO add your handling code here:
        int row = jTableSPCT.getSelectedRow();
        fillDataCTSP(row);
    }//GEN-LAST:event_jTableSPCTMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCTSP;
    private javax.swing.JButton btnAddSP;
    private javax.swing.JButton btnNewCTSP;
    private javax.swing.JButton btnNewSanPham;
    private javax.swing.JButton btnUpdateCTSP;
    private javax.swing.JButton btnUpdatesanPham;
    private javax.swing.JButton btndeleteCTSP;
    private javax.swing.JButton btndeletesanPham;
    private javax.swing.JComboBox<String> cbbIDDongSp;
    private javax.swing.JComboBox<String> cbbIDMauSac;
    private javax.swing.JComboBox<String> cbbIDNSX;
    private javax.swing.JComboBox<String> cbbIDSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSPCT;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDCTSP;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNBH;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtsoLuong;
    // End of variables declaration//GEN-END:variables
}
